# Generated by Django 6.0.2 on 2026-02-14 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Provider",
                "verbose_name_plural": "LLM Providers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("context_window", models.IntegerField(blank=True, null=True)),
                ("input_cost_per_1k", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("output_cost_per_1k", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="models", to="llm_chat.llmprovider")),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ("provider", "name"),
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("is_archived", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ("-updated_at",),
                "indexes": [models.Index(fields=["user", "updated_at"], name="llm_chat_conv_user_upd_idx")],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("system", "System"), ("user", "User"), ("assistant", "Assistant"), ("tool", "Tool")], max_length=20)),
                ("content", models.TextField()),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("input_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("output_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("total_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="llm_chat.conversation")),
                ("model_used", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="llm_chat.llmmodel")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["conversation", "created_at"], name="llm_chat_msg_conv_created_idx"),
                    models.Index(fields=["role"], name="llm_chat_msg_role_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLLMPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("temperature", models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ("top_p", models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("system_prompt", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_model", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="user_preferences", to="llm_chat.llmmodel")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="llm_preference", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User LLM Preference",
                "verbose_name_plural": "User LLM Preferences",
                "ordering": ("-updated_at",),
            },
        ),
    ]
