# Generated by Django 6.0.2 on 2026-02-14 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import utils.encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="auth_type",
            field=models.CharField(
                choices=[("api_key", "API Key")],
                default="api_key",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="base_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="supports_openai_compatible",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="UserProviderCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                ("secret", utils.encrypted_field.EncryptedTextField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_credentials", to="llm_chat.llmprovider")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="provider_credentials", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Provider Credential",
                "verbose_name_plural": "User Provider Credentials",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="message",
            name="credential_used",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="llm_chat.userprovidercredential"),
        ),
        migrations.AddField(
            model_name="userllmpreference",
            name="default_credential",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="preferences", to="llm_chat.userprovidercredential"),
        ),
        migrations.AddConstraint(
            model_name="userprovidercredential",
            constraint=models.UniqueConstraint(fields=("user", "provider", "label"), name="llm_chat_user_provider_label_uniq"),
        ),
    ]
