# Generated by Django 5.2.11 on 2026-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0002_userprovidercredential_and_provider_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('streaming', 'Streaming (in progress)'), ('completed', 'Completed'), ('error', 'Error')], default='completed', help_text='Message status: streaming (in progress), completed, or error.', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time for streaming status/completion tracking.'),
        ),
    ]
